---
- name: Deploy My Project in a Docker Container
  hosts: bastion_host
  become: true
  tasks:
    - name: Updating apt
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker Service
      service:
        name: docker
        state: started

    - name: Deploy Docker Container
      command: docker run -itd -p 3010:3010 sejalmm06/aquilacms:latest
