---
- name: Deploy Docker Containers
  hosts: localhost  # You can specify the target hosts here

  tasks:
    - name: Copy Docker Compose File
      copy:
        src: "{{ DOCKER_COMPOSE_FILE }}"
        dest: docker-compose.yml
      when: DOCKER_COMPOSE_FILE is defined

    - name: Pull Docker Images
      loop:
        - "{{ DOCKER_HUB_USER }}/{{ item }}:{{ DOCKER_TAG }}"
      docker_image:
        name: "{{ item }}"
        source: pull
      when: DOCKER_HUB_USER is defined and DOCKER_TAG is defined
      loop_control:
        loop_var: item

    - name: Start Docker Containers
      loop:
        - "{{ DOCKER_HUB_USER }}/{{ item }}:{{ DOCKER_TAG }}"
      docker_container:
        name: "{{ item }}"
        image: "{{ item }}"
        state: started
        restart_policy: always
      when: DOCKER_HUB_USER is defined and DOCKER_TAG is defined
      loop_control:
        loop_var: item

    - name: Ensure Docker Compose Services are Running
      command: docker-compose -f docker-compose.yml up -d
      args:
        creates: docker-compose.yml  # Check if the file exists
      when: DOCKER_COMPOSE_FILE is defined
